region = "us-central1"
gcp_project = "cloudglobaldelivery-1000135575"
credentials= "credentials.json"
zone = "us-central1-a"
instance_name = "terraform-instance1"
target-pool = "instance1-target-pool"
health-check = "instance-health-check"
